Add skip_init_quotas param
selectel/python-selvpcclient pull request #32
Opened 2023-03-30 17:10 UTC by T-Sh

Add param "skip_init_quotas" in project's creation.
skip_init_quotas allows to disable quotas initialization for created project.

2023-03-30 21:50 UTC, milkrage requested changes

2023-03-30 21:50 UTC, milkrage commented on selvpcclient/commands/project.py
> +                              action='store_true'
Я верно понимаю, что эта строка возвращает дефолтное значение True? Если так, то это противоречит схеме.

2023-03-31 08:45 UTC, T-Sh commented on selvpcclient/commands/project.py
> +                              action='store_true'
Если не указать skip_quotas_init в команде, дефолтным значением будет False (указан в default). action='store_true' означает, что аргумент принимает только 2 значения (True/False).

2023-03-31 15:46 UTC, milkrage approved these changes

2023-04-10 14:54 UTC, merged